name: "latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *" # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "Hashnode Blogs"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: "Sahil17" # Hashnode Username
          COUNT: 2 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://operationsguy.hashnode.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

