# name: "Blog Updater"

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *' # Runs Every Day

# jobs:
#   update_blogs:
#     name: "Update Blogs"
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Fetching Repository Contents"
#         uses: actions/checkout@main

#       - name: "Hashnode Blogs"
#         uses: "varunsridharan/action-hashnode-blog@main"
#         with:
#           USERNAME: 'Sahil17' # Hashnode Username
#           BLOG_URL: 'https://operationsguy.hashnode.dev/' # Blog URL
#           COUNT: 2 # MAX Visisble
#           STYLE: "blog-alternate"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

